apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.werf.yml -o ./.helm/templates
    kompose.service.expose: actix-yew-oidc.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: actix-yew-oidc-web
  name: actix-yew-oidc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: actix-yew-oidc-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.werf.yml -o ./.helm/templates
        kompose.service.expose: actix-yew-oidc.test
        kompose.service.expose.ingress-class-name: nginx
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/actix-yew-oidc-network: "true"
        io.kompose.service: actix-yew-oidc-web
    spec:
      containers:
        - env:
            - name: REACT_APP_BACKEND_URL
              value: http://backend.actix-yew-oidc.test
            - name: REACT_APP_KEYCLOAK_CLIENT_ID
              value: react
            - name: REACT_APP_KEYCLOAK_URL
              value: http://keycloak.actix-yew-oidc.test/realms/actix-yew-demo
          image: {{ .Values.werf.image.actix_yew_oidc_web }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3000
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
          name: actix-yew-oidc-web
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
