apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.werf.yml -o ./.helm/templates
    kompose.service.expose: backend.actix-yew-oidc.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: actix-yew-oidc-backend
  name: actix-yew-oidc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: actix-yew-oidc-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.werf.yml -o ./.helm/templates
        kompose.service.expose: backend.actix-yew-oidc.test
        kompose.service.expose.ingress-class-name: nginx
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/actix-yew-oidc-network: "true"
        io.kompose.service: actix-yew-oidc-backend
    spec:
      containers:
        - env:
            - name: AUTHORITY
              value: http://actix-yew-oidc-keycloak/realms/actix-yew-demo
          image: {{ .Values.werf.image.actix_yew_oidc_backend }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/healthcheck
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
          name: actix-yew-oidc-backend
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
